name: Playwright Tests
on:
    pull_request:
        branches: [main]
    workflow_dispatch:
        inputs:
            logLevel:
                description: 'Log level'
                required: true
                default: 'warning'
            tags:
                description: 'Manual scenario'
jobs:
    e2e-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.1.1
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'npm'
            - name: Install dependencies
              run: |
                  npm ci
                  npx playwright install
            - name: Run Playwright Tests
              env:
                  USER_EMAIL: ${{secrets.USER_EMAIL}}
                  USER_PASSWORD: ${{secrets.USER_PASSWORD}}
              run: |
                  npx playwright test
            - uses: actions/upload-artifact@v4
              with:
                  name: allure-results
                  path: allure-results
                  retention-days: 5
            - name: Get Allure history
              uses: actions/checkout@v4
              if: always()
              continue-on-error: true
              with:
                  ref: gh-pages
                  path: gh-pages
            - name: Allure Reports
              uses: simple-elf/allure-report-action@v1.6
              if: always()
              id: allure-report
              with:
                  allure_results: allure-results
                  gh_pages: gh-pages
                  allure_report: allure-report
                  allure_history: allure-history
                  keep_reports: 5
            - name: Deploy report to Github Pages
              if: always()
              uses: peaceiris/actions-gh-pages@v2
              env:
                  PERSONAL_TOKEN: ${{secrets.GITHUB_TOKEN}}
                  PUBLISH_BRANCH: gh-pages
                  PUBLISH_DIR: allure-history